[package]
name = "wallabag-api"
version = "0.1.0"
authors = ["Samuel Walladge <samuel@swalladge.id.au>"]
edition = "2018"

[dependencies]

# TODO: restrict versions
reqwest = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
