[package]
name = "wallabag-api"
version = "0.1.0"
authors = ["Samuel Walladge <samuel@swalladge.id.au>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.6", features = ["serde"] }
log = "0.4.6"
reqwest = "0.9.5"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.33"
